### PR TITLE
feat: default to monotonic generation

### PR DESCRIPTION
**Pull request by grempe**
This commit addresses issue https://github.com/ryan-mars/ulid-workers/issues/5 and modernizes the code, dev dependencies, and test suite for this library.

NOTE : I re-opened this PR after closing previous PR due to issues getting git/github to treat the history as I wanted.  It seems that github may be insisting to "lose" history by displaying renamed files with significant changes as deleted and moved instead of renamed.  I don't think I can resolve this display issue.

You can browse the new code and README here:

https://github.com/grempe/ulid-workers/tree/cloudflare

Here are the major changes spread across a few commits. Due to the API change to support factory functions in all cases this would be a v2.0.0 release. I updated the CHANGELOG.md as well, but you'll need to update the date.

Use a factory function that returns a function for both monotonic and non-monotonic uses.
Default to using monotonic ULID generation
Fully remove PRNG agility. Always use crypto.getRandomValues()
Allow passing timestamp argument to both monotonic and non-monotonic ulid() functions
Stop public export of private functions, provide them only to test suite
Modernize all dev dependencies
Convert Mocha test suite and runner to Typescript
No longer require build from Typescript to JS to test
Expand test coverage
Update README for clarity and to reflect Cloudflare use case
Modernize Husky git pre-commit toolchain
Please let me know if you have any questions/concerns.

### CODE REVIEW

**Comment by grempe** [comment]
cc: @peterbourgon

**Comment by grempe** [comment]
FYI : the full diff to the `src` and `test` files is available when you narrow the view to that single commit.  Github's multi-commit summary view treats it as a delete+add.

See here to view the actual changes:
https://github.com/ryan-mars/ulid-workers/pull/7/commits/9e7c9ce4c679e2e859cb1584373bf2a901a91efc

**Comment by ryan-mars** [comment]
@grempe Added to v2.0.0

**Comment by peterbourgon** [comment]
It looks like if you give this function a ULID with the entropy section maxed out, it will roll the entropy over to zero, and increment the timestamp by 1ms.

```
$ ulid 01FVJFV41BZZZZZZZZZZZZZZZZ
Thu Feb 10 18:55:29.835 UTC 2022

$ incrementBase32('01FVJFV41BZZZZZZZZZZZZZZZZ')
01FVJFV41C0000000000000000

$  ulid 01FVJFV41C0000000000000000
Thu Feb 10 18:55:29.836 UTC 2022
```

Oops!

**Pull request merged**
